pool:
  vmImage: 'macos-latest'

stages:
  - stage: E2E
    jobs:
      - job: Run_E2E_Tests
        steps:
          - script: yarn

          - script: yarn global add detox-cli
            displayName: Install Detox

          - script: |
              echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;default;x86_64"
              echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name Pixel_API_30_AOSP --device "pixel_4" -k 'system-images;android-30;default;x86_64'
              $ANDROID_HOME/emulator/emulator -list-avds
            condition: ne(variables.AVD_IMAGES_RESTORED, 'true')
            displayName: 'Download Android Emulator Image'

          - script: |
              echo "Android: Building the project for Detox tests..."
              npx detox build --configuration android.emu.release --loglevel verbose

              echo "Android: Executing Detox tests..."
              npx detox test --configuration android.emu.release --headless --loglevel verbose
            displayName: 'Build app for tests'

